=== santthosh/dre-framework/dre-framework/DRE/resources/edu/ncsu/dre/test/configuration.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="EngineConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Segregator" type="Component"/>          
        <xs:element name="ResearchScheduler" type="Component"/>
        <xs:element name="Aggregator" type="Component"/>
        <xs:element maxOccurs="unbounded" minOccurs="1" name="ServiceProvider" type="Component"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="Parameter" type="Arguments"/> 
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Component">
    <xs:sequence>
      <xs:element name="Handler" nillable="false" type="xs:string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="Option" type="Arguments"/>        
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Arguments">
    <xs:sequence/>
    <xs:attribute name="key" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>
  </xs:complexType>
</xs:schema>

=== santthosh/dre-framework/dre-framework/DRE/DummySegregatorConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<EngineConfiguration> 
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" 
  xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="configuration.xsd">  
  <Segregator>
  	<Handler>edu.ncsu.dre.impl.engine.DummySegregator</Handler>
  	<Option key="Comment" value="This is the LexicalSegregator"/>
  	</Segregator>
  <ResearchScheduler>
  	<Handler>edu.ncsu.dre.impl.engine.StandAloneScheduler</Handler>
  	<Option key="Comment" value="This is the StandAloneScheduler"/>
  </ResearchScheduler>
  <Aggregator>
  	<Handler>edu.ncsu.dre.impl.engine.XMLAggregator</Handler>
  	<Option key="Comment" value="This is the XMLAggregator"/>
  </Aggregator> 
  <ServiceProvider>
  	<Handler>edu.ncsu.dre.impl.engine.LiveSearchProvider</Handler>
  	<Option key="AppID" value="7E8E2A6CDEEE7248E0EBF23EDD20303F86364CCE"/>
  	<Option key="Culture" value="en-US"/>
  	<Option key="SafeSearch" value="Off"/>
  	<Option key="Source" value="web"/>	<!-- value="Ads/Image/InlineAnswers/News/PhoneBook/QueryLocation/Spelling/Web/WordBreaker" -->  	
  </ServiceProvider>  
  <Parameter key="Comment" value="SimpleStandAlone DRE Framework."/>
</EngineConfiguration>

=== santthosh/dre-framework/trunk/dre-framework/DRE/conf/YahooProviderConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<EngineConfiguration> 
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" 
  xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="configuration.xsd">  
  <Segregator>
  	<Handler>edu.ncsu.dre.impl.engine.DummySegregator</Handler>
  	<Option key="Comment" value="This is the LexicalSegregator"/>
  	</Segregator>
  <ResearchScheduler>
  	<Handler>edu.ncsu.dre.impl.engine.StandAloneScheduler</Handler>
  	<Option key="Comment" value="This is the StandAloneScheduler"/>
  </ResearchScheduler>
  <Aggregator>
  	<Handler>edu.ncsu.dre.impl.engine.XMLAggregator</Handler>
  	<Option key="Comment" value="This is the XMLAggregator"/>
  </Aggregator> 
  <ServiceProvider>
  	<Handler>edu.ncsu.dre.impl.engine.YahooSearchProvider</Handler>
  	<Option key="AppID" value="eCBIC3LV34EN3FHl35AMrMhA7JoOi4jfPPy1VQrSNr51qWbeO43DkDDLSqG0jmVg"/>  	
  	<Option key="ID" value="Yahoo"/>
  </ServiceProvider> 
  <Parameter key="Comment" value="Yahoo Search Provider Configuration."/>
</EngineConfiguration>

=== santthosh/dre-framework/trunk/dre-framework/DRE/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<EngineConfiguration> 
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" 
  xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="configuration.xsd">  
  <Segregator>
  	<Handler>edu.ncsu.dre.impl.engine.LexicalSegregator</Handler>
  	<Option key="Comment" value="This is the LexicalSegregator"/>
  	</Segregator>
  <ResearchScheduler>
  	<Handler>edu.ncsu.dre.impl.engine.StandAloneScheduler</Handler>
  	<Option key="Comment" value="This is the StandAloneScheduler"/>
  </ResearchScheduler>
  <Aggregator>
  	<Handler>edu.ncsu.dre.impl.engine.XMLAggregator</Handler>
  	<Option key="Comment" value="This is the XMLAggregator"/>
  </Aggregator> 
  <ServiceProvider>
  	<Handler>edu.ncsu.dre.impl.engine.LiveSearchProvider</Handler>
  	<Option key="web" value="true"/>
  </ServiceProvider>  
  <Parameter key="Comment" value="SimpleStandAlone DRE Framework."/>
</EngineConfiguration>
